* SM2
  https://www.supermemo.com/en/archives1990-2015/english/ol/sm2

** easiness_factor
   - E-Factors were allowed to vary between 1.1 for the most difficult items and 2.5 for the easiest ones.
   - At the moment of introducing an item into a SuperMemo database, its E-Factor was assumed to equal 2.5
   - In the course of repetitions this value was gradually decreased in case of recall problems. Thus the greater problems an item caused in recall, the more significant was the decrease of its E-Factor.

      I noticed that E-Factors should not fall below the value of 1.3. Items having E-Factors lower than 1.3 were repeated annoyingly often and always seemed to have inherent flaws in their formulation (usually they did not conform to the minimum information principle). Thus not letting E-Factors fall below 1.3 substantially improved the throughput of the process and provided an indicator of items that should be reformulated. The formula used in calculating new E-Factors for items was constructed heuristically and did not change much in the following 3.5 years of using the computer-based SuperMemo method.


   easiness_factor: 1.3 ... 2.5

   --------------------------------------------------------------------------------

   EF':=f(EF,q)

   where:

   EF' - new value of the E-Factor
   EF - old value of the E-Factor
   q - quality of the response
   f - function used in calculating EF'.

   --------------------------------------------------------------------------------


    EF':=EF-0.8+0.28*q-0.02*q*q

which is a reduced form of:

    EF':=EF+(0.1-(5-q)*(0.08+(5-q)*0.02))
