import React from 'react';
import { useMarkupValue } from '../lib/MarkupProvider';

// build the React structure from the AST generated by rust
//
export function buildMarkup(content) {
  const markup = useMarkupValue();
  const astArray = markup.asHtmlAst(content);

  return astArray.map(compile);
}

function compile(n) {
  return n.name === "text" ? n.text : React.createElement(n.name, attrs(n), ...n.children.map(compile));
}

function attrs(n) {
  return {
    key: n.key,
    className: n.class_name,
    htmlFor: n.html_for,
    href: n.href,
    type: n.html_type,
    id: n.id
  }
}
