import React from 'react';
import { useMarkupValue } from '../lib/MarkupProvider';

// build the React structure from the AST generated by rust
//
export function buildMarkup(content) {
  const markup = useMarkupValue();
  const astArray = markup.asHtmlAst(content);

  return astArray.map(compile);
}

function compile(n) {
  return n.name === "text" ? n.text : React.createElement(n.name, buildProps(n), ...n.children.map(compile));
}

function buildProps(node) {
  let res = {};

  if (node.key !== null) {
    res.key = node.key;
  }
  if (node.class_name !== null) {
    res.className = node.class_name;
  }
  if (node.html_for !== null) {
    res.htmlFor = node.html_for;
  }
  if (node.href !== null) {
    res.href = node.href;
  }
  if (node.html_type !== null) {
    res.type = node.html_type;
  }
  if (node.id !== null) {
    res.id = node.id;
  }

  return res;
}
