import { Font } from "../enums";

export default function FontSelector({
    font,
    onChangedFont,
}: {
    font: Font;
    onChangedFont: (font: Font) => void;
}) {
    function onChange(e: Event) {
        if (e.target instanceof HTMLSelectElement) {
            const font = parseInt(e.target.value, 10) as Font;
            onChangedFont(font);
        }
    }

    return (
        <span class="c-font-selector ui">
            <select onChange={onChange}>
                <option
                    class="typeface-serif font-size-2rem"
                    value={Font.Serif}
                    selected={font === Font.Serif}
                >
                    Serif &mdash; boring, default
                </option>
                <option
                    class="typeface-sans font-size-2rem"
                    value={Font.Sans}
                    selected={font === Font.Sans}
                >
                    Sans &mdash; for modern, social media sources
                </option>
                <option
                    class="typeface-cursive  font-size-2rem"
                    value={Font.Cursive}
                    selected={font === Font.Cursive}
                >
                    Cursive &mdash; handwritten
                </option>
                <option
                    class="typeface-ai  font-size-2rem"
                    value={Font.AI}
                    selected={font === Font.AI}
                >
                    AI &mdash; content generated by machines
                </option>
                <option
                    class="typeface-french-canon-body  font-size-2rem"
                    value={Font.FrenchCanon}
                    selected={font === Font.FrenchCanon}
                >
                    French Canon &mdash; fairly old text
                </option>
                <option
                    class="typeface-english-body  font-size-2rem"
                    value={Font.English}
                    selected={font === Font.English}
                >
                    English &mdash; even older text
                </option>
                <option
                    class="typeface-de-walpergens-body  font-size-2rem"
                    value={Font.DeWalpergens}
                    selected={font === Font.DeWalpergens}
                >
                    De Walpergens &mdash; ancient text
                </option>
                <option
                    class="typeface-double-pica-body  font-size-2rem"
                    value={Font.DoublePica}
                    selected={font === Font.DoublePica}
                >
                    Double Pica &mdash; nice, old book
                </option>
                <option
                    class="typeface-great-primer-body  font-size-2rem"
                    value={Font.GreatPrimer}
                    selected={font === Font.GreatPrimer}
                >
                    Great Primer &mdash; slightly more moden book
                </option>
                <option
                    class="typeface-three-lines-pica  font-size-2rem"
                    value={Font.ThreeLinesPica}
                    selected={font === Font.ThreeLinesPica}
                >
                    Three Lines Pica &mdash; book, but harder to read
                </option>
                <option
                    class="typeface-libre-baskerville  font-size-2rem"
                    value={Font.LibreBaskerville}
                    selected={font === Font.LibreBaskerville}
                >
                    Libre Baskerville &mdash; default beautiful typeface
                </option>
                <option
                    class="typeface-essays-1743  font-size-2rem"
                    value={Font.Essays1743}
                    selected={font === Font.Essays1743}
                >
                    Essays1743 &mdash; default 18th Century typeface
                </option>
                <option
                    class="typeface-hyperlegible  font-size-2rem"
                    value={Font.Hyperlegible}
                    selected={font === Font.Hyperlegible}
                >
                    Hyperlegible &mdash; improved legibility and readability
                </option>
            </select>
        </span>
    );
}
