import { Font } from "../enums";

export default function FontSelector({
    font,
    onChangedFont,
}: {
    font: Font;
    onChangedFont: (font: Font) => void;
}) {
    function onChange(e: Event) {
        if (e.target instanceof HTMLSelectElement) {
            const font = parseInt(e.target.value, 10) as Font;
            onChangedFont(font);
        }
    }

    return (
        <span class="c-font-selector ui">
            <select onChange={onChange}>
                <option
                    class="typeface-serif font-size-2rem"
                    value={Font.Serif}
                    selected={font === Font.Serif}
                >
                    Serif &mdash; boring, default
                </option>
                <option
                    class="typeface-sans font-size-2rem"
                    value={Font.Sans}
                    selected={font === Font.Sans}
                >
                    Sans &mdash; for modern, social media sources
                </option>
                <option
                    class="typeface-cursive  font-size-2rem"
                    value={Font.Cursive}
                    selected={font === Font.Cursive}
                >
                    Cursive &mdash; handwritten
                </option>
                <option
                    class="typeface-ai  font-size-2rem"
                    value={Font.AI}
                    selected={font === Font.AI}
                >
                    AI &mdash; content generated by machines
                </option>
                <option
                    class="typeface-de-walpergens-body  font-size-2rem"
                    value={Font.DeWalpergens}
                    selected={font === Font.DeWalpergens}
                >
                    De Walpergens &mdash; ancient text
                </option>
                <option
                    class="typeface-essays-1743  font-size-2rem"
                    value={Font.Essays1743}
                    selected={font === Font.Essays1743}
                >
                    Essays1743 &mdash; default 18th Century typeface
                </option>
                <option
                    class="typeface-hyperlegible  font-size-2rem"
                    value={Font.Hyperlegible}
                    selected={font === Font.Hyperlegible}
                >
                    Hyperlegible &mdash; improved legibility and readability
                </option>
            </select>
        </span>
    );
}
